name: flightbooker-frontend deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "Flightbooker/flightbooker-frontend/**"
      - ".github/workflows/build-deploy-frontend.yaml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrmicrohack1.azurecr.io
          username: ${{ secrets.FLIGHTBOOKER_REGISTRY_USERNAME }}
          password: ${{ secrets.FLIGHTBOOKER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: azure/docker-login@v1
        with:
          login-server: acrmicrohack1.azurecr.io
          username: ${{ secrets.FLIGHTBOOKER_REGISTRY_USERNAME }}
          password: ${{ secrets.FLIGHTBOOKER_REGISTRY_PASSWORD }}
      - run: |
          cd Flightbooker/flightbooker-frontend
          docker build . -t acrmicrohack1.azurecr.io/flightbookerfrontend:latest
          docker push acrmicrohack1.azurecr.io/flightbookerfrontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FLIGHTBOOKER_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n flightbooker-frontend -g rg-microhack1 --server acrmicrohack1.azurecr.io --username  ${{ secrets.FLIGHTBOOKER_REGISTRY_USERNAME }} --password ${{ secrets.FLIGHTBOOKER_REGISTRY_PASSWORD }}
            az containerapp update -n flightbooker-frontend -g rg-microhack1 --image acrmicrohack1.azurecr.io/flightbookerfrontend:latest
